import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import '../styles/globals.css'

import { Footer } from '@/components/Footer/Footer'
import { Header } from '@/components/Header/Header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full min-h-screen max-w-screen flex flex-col items-center`}
      >
        <Header />
        <main className="w-full max-w-[1440px] p-4 flex flex-grow mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
